name: ripple_rest
version: 0.6.0+1
author: George Moschovitis <george.moschovitis@gmail.com>
description: A wrapper around the Ripple REST API.
homepage: https://github.com/gmosx/dart-ripple_rest
dependencies:
  http: '>=0.11.1+1 <0.12.0'
dev_dependencies:
  unittest: any
